server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testDB

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:database.changelog/database.changelog.master.xml